version: "3.8"

services:
  postgres:
    container_name: "postgres"
    image: postgres:13.2-alpine
    restart: always
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: hh
      POSTGRES_DB: hh
      POSTGRES_USER: hh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hh"]
      interval: 10s
      timeout: 5s
      retries: 5
